import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, Check, FileImage, FileText, ImagePlus, Layers3, LockKeyhole, Settings2, Sparkles, Trash2, Upload, X, GripVertical } from 'lucide-react'
import { deleteExam, itemToPreviewUrl, saveExam, type ExamRecord, type PaperItem, type PaperSide, getExam } from './db'

function Workspace({title,description,side,items,onChange}:{title:string;description:string;side:PaperSide;items:PaperItem[];onChange:(items:PaperItem[])=>void}){
 const inputRef=useRef<HTMLInputElement>(null);const [dragging,setDragging]=useState(false)
 const addImages=(files:FileList|null)=>{if(!files)return;const next:Array<PaperItem>=Array.from(files).filter(f=>f.type.startsWith('image/')).map(f=>({id:crypto.randomUUID(),type:'image',blob:f,name:f.name,mimeType:f.type,size:f.size,createdAt:Date.now()}));onChange([...items,...next]);if(inputRef.current)inputRef.current.value=''}
 const addText=()=>{const text=window.prompt(side==='questions'?'Paste or type part of the question paper:':'Paste or type part of your solution:');if(text?.trim())onChange([...items,{id:crypto.randomUUID(),type:'text',text:text.trim(),createdAt:Date.now()}])}
 const move=(i:number,d:-1|1)=>{const n=[...items],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];onChange(n)}
 return <section className={`workspace ${dragging?'workspace--dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);addImages(e.dataTransfer.files)}}>
  <div className="workspace__head"><div><div className="eyebrow">Workspace</div><h2>{title}</h2><p>{description}</p></div><span className="count-pill">{items.length} {items.length===1?'item':'items'}</span></div>
  <div className="dropzone"><div className="dropzone__icon"><Upload size={20}/></div><div className="dropzone__copy"><strong>Drop anything here</strong><span>Images, text, or a mixture of both.</span></div><div className="dropzone__actions"><button className="button" onClick={()=>inputRef.current?.click()}><ImagePlus size={16}/> Add photos</button><button className="button" onClick={addText}><FileText size={16}/> Add text</button></div><input ref={inputRef} hidden type="file" accept="image/*" multiple onChange={e=>addImages(e.target.files)}/></div>
  {items.length>0&&<div className="item-grid">{items.map((item,i)=>{const url=itemToPreviewUrl(item);return <article className={`paper-item paper-item--${item.type}`} key={item.id}><div className="item-tools"><button disabled={i===0} aria-label="Move earlier" onClick={()=>move(i,-1)}>↑</button><button disabled={i===items.length-1} aria-label="Move later" onClick={()=>move(i,1)}>↓</button><button aria-label="Remove item" onClick={()=>{if(url)URL.revokeObjectURL(url);onChange(items.filter(x=>x.id!==item.id))}}>×</button></div>{item.type==='image'?<><img src={url} alt={item.name}/><div className="item-meta"><FileImage size={14}/><span title={item.name}>{item.name}</span></div></>:<><div className="text-item__mark">T</div><p>{item.text}</p><div className="item-meta"><FileText size={14}/><span>Text block</span></div></>}</article>})}</div>}
 </section>
}
export default function App(){
 const [exam,setExam]=useState<ExamRecord>({id:crypto.randomUUID(),title:'',subject:'',totalMarks:null,createdAt:Date.now(),updatedAt:Date.now(),questions:[],answers:[]})
 const [loaded,setLoaded]=useState(false);const [showSettings,setShowSettings]=useState(false);const [saved,setSaved]=useState(false)
 useEffect(()=>{const raw=localStorage.getItem('paper-examiner-current');if(!raw){setLoaded(true);return}try{const id=JSON.parse(raw).id;getExam(id).then(x=>x&&setExam(x)).finally(()=>setLoaded(true))}catch{setLoaded(true)}},[])
 useEffect(()=>{if(!loaded)return;const t=setTimeout(()=>{saveExam({...exam,updatedAt:Date.now()}).then(()=>{localStorage.setItem('paper-examiner-current',JSON.stringify({id:exam.id}));setSaved(true);setTimeout(()=>setSaved(false),900)}).catch(()=>{})},400);return()=>clearTimeout(t)},[exam,loaded])
 const ready=exam.questions.length>0&&exam.answers.length>0;const images=useMemo(()=>[...exam.questions,...exam.answers].filter(x=>x.type==='image').length,[exam])
 const update=(side:PaperSide,v:PaperItem[])=>setExam(e=>({...e,[side]:v,updatedAt:Date.now()}))
 const reset=async()=>{if(!confirm('Delete this evaluation and all of its local paper data?'))return;await deleteExam(exam.id);localStorage.removeItem('paper-examiner-current');location.reload()}
 return <main className="app-shell"><nav className="topbar"><div className="brand"><div className="brand__mark"><Layers3 size={18}/></div><span>Paper Examiner</span></div><div className="topbar__right"><span className="privacy"><LockKeyhole size={14}/> {saved?'Saved locally':'Local-first'}</span><button className="icon-button" aria-label="Settings" onClick={()=>setShowSettings(true)}><Settings2 size={18}/></button></div></nav>
 <div className="content"><header className="hero"><div className="hero__copy"><div className="eyebrow"><Sparkles size={14}/> Private AI evaluation workspace</div><h1>Put in the paper.<br/><em>Get the verdict.</em></h1><p>Drop the original questions and your solved work. Organize nothing manually — Paper Examiner will understand the paper later.</p></div><div className="hero__status"><div className="status-card"><span>Evaluation readiness</span><strong>{ready?'Ready to review':'Add both papers'}</strong><div className="status-line"><i className={ready?'is-ready':''}/></div><small>{exam.questions.length} question-side items · {exam.answers.length} solution-side items</small></div></div></header>
 <section className="exam-meta"><div><label>Paper name</label><input value={exam.title} onChange={e=>setExam(x=>({...x,title:e.target.value,updatedAt:Date.now()}))} placeholder="e.g. Physics Chapter Test"/></div><div><label>Subject <span>optional</span></label><input value={exam.subject} onChange={e=>setExam(x=>({...x,subject:e.target.value,updatedAt:Date.now()}))} placeholder="e.g. Physics"/></div><div><label>Total marks <span>optional</span></label><input type="number" min="0" value={exam.totalMarks??''} onChange={e=>setExam(x=>({...x,totalMarks:e.target.value===''?null:Number(e.target.value),updatedAt:Date.now()}))} placeholder="50"/></div></section>
 <div className="workspace-stack"><Workspace title="Question Paper" description="Add the complete original paper in any order — photos, text, or both." side="questions" items={exam.questions} onChange={v=>update('questions',v)}/><div className="flow-divider"><span>then</span><ArrowUpRight size={16}/></div><Workspace title="Your Solution" description="Drop your complete submitted work. Don't split it into questions manually." side="answers" items={exam.answers} onChange={v=>update('answers',v)}/></div>
 <section className="launch-card"><div><div className="eyebrow">Phase 1 · local foundation</div><h3>{ready?'Your paper is locally saved.':'Start by adding both sides.'}</h3><p>{images} image{images===1?'':'s'} stored in this browser · {saved?'Autosaved just now.':'Changes autosave locally.'}</p></div><button className="button button--primary" disabled={!ready} onClick={()=>setShowSettings(true)}>Examiner settings <ArrowUpRight size={17}/></button></section><button className="danger-link" onClick={reset}><Trash2 size={14}/> Delete local evaluation</button></div>
 {showSettings&&<div className="modal-backdrop" onMouseDown={()=>setShowSettings(false)}><div className="modal modal--setup" onMouseDown={e=>e.stopPropagation()}><div className="modal__head"><div><div className="eyebrow">Local data</div><h3>Paper settings</h3></div><button className="icon-button" onClick={()=>setShowSettings(false)}><X size={18}/></button></div><div className="setup-preview"><div><Check size={16}/><span>Paper images live in IndexedDB</span></div><div><Check size={16}/><span>Exam metadata autosaves locally</span></div><div><Check size={16}/><span>No application backend is used</span></div><div><Check size={16}/><span>Clear site data removes local data</span></div></div><button className="button button--primary button--full" onClick={()=>setShowSettings(false)}>Done</button></div></div>}</main>
}